TOPICS = [
    {
        "id": "spark",
        "title": "Spark Fundamentals",
        "description": "Learn Apache Spark basics and data processing",
        "icon": "⚡",
        "lesson_ids": ["spark_intro", "spark_dataframes", "spark_ops"],
    },
    {
        "id": "delta",
        "title": "Delta Lake",
        "description": "Master ACID transactions and data reliability",
        "icon": "🏔️",
        "lesson_ids": ["delta_intro", "delta_acid", "delta_timetravel"],
    },
    {
        "id": "mlflow",
        "title": "MLflow",
        "description": "Track and manage machine learning models",
        "icon": "🎛️",
        "lesson_ids": ["mlflow_tracking", "mlflow_registry"],
    },
    {
        "id": "unity",
        "title": "Unity Catalog",
        "description": "Govern data and AI assets across your platform",
        "icon": "📚",
        "lesson_ids": ["unity_intro", "unity_namespace"],
    },
]

LESSONS = {
    "spark_intro": {
        "id": "spark_intro",
        "title": "Introduction to Spark",
        "description": "Understand the basics of Apache Spark",
        "xp_reward": 100,
        "topic_id": "spark",
        "exercises": [
            {
                "id": "spark_intro_1",
                "type": "multiple_choice",
                "question": "What is Apache Spark?",
                "options": [
                    "A distributed SQL database",
                    "A unified analytics engine for large-scale data processing",
                    "A Python data library",
                    "A data visualization tool",
                ],
                "correct_answer": 1,
                "explanation_correct": "Spark is a unified analytics engine — it handles batch, streaming, ML, and graph workloads on distributed clusters.",
                "explanation_wrong": "Spark is not a database or visualization tool. It's a distributed processing engine that runs workloads across a cluster of machines.",
            },
            {
                "id": "spark_intro_2",
                "type": "multiple_choice",
                "question": "What is the primary abstraction in Spark?",
                "options": [
                    "DataFrame",
                    "RDD (Resilient Distributed Dataset)",
                    "Both A and B",
                    "Neither A nor B",
                ],
                "correct_answer": 2,
                "explanation_correct": "Spark has two primary abstractions: the low-level RDD and the high-level DataFrame (which is built on top of RDDs).",
                "explanation_wrong": "Both are correct — RDDs are the foundational abstraction, while DataFrames provide a higher-level structured API built on top of them.",
            },
            {
                "id": "spark_intro_3",
                "type": "fill_blank",
                "question": "Spark is _______ resistant, meaning it can recover from node failures.",
                "correct_answer": "fault",
                "explanation_correct": "Fault tolerance is a core Spark property — RDDs track their lineage so any lost partition can be recomputed from the original data.",
                "explanation_wrong": "The answer is 'fault'. Spark is fault-tolerant because it records the sequence of transformations (lineage) needed to rebuild any lost data partition.",
            },
        ],
    },
    "spark_dataframes": {
        "id": "spark_dataframes",
        "title": "Spark DataFrames",
        "description": "Work with structured data using DataFrames",
        "xp_reward": 100,
        "topic_id": "spark",
        "exercises": [
            {
                "id": "spark_df_1",
                "type": "multiple_choice",
                "question": "Which method creates a DataFrame from a Pandas DataFrame?",
                "options": [
                    "spark.createDataFrame()",
                    "spark.from_pandas()",
                    "pd.to_spark()",
                    "spark.DataFrame()",
                ],
                "correct_answer": 0,
                "explanation_correct": "spark.createDataFrame() accepts a Pandas DataFrame (or list/RDD) and returns a Spark DataFrame distributed across the cluster.",
                "explanation_wrong": "The correct method is spark.createDataFrame(). Methods like from_pandas() and to_spark() don't exist in the standard Spark API.",
            },
            {
                "id": "spark_df_2",
                "type": "fill_blank",
                "question": "The _______ method is used to display DataFrame contents in a formatted way.",
                "correct_answer": "show",
                "explanation_correct": "df.show() prints the first 20 rows by default in a formatted table. You can pass a number to control how many rows are displayed.",
                "explanation_wrong": "The answer is 'show'. df.show() is the standard way to preview DataFrame contents — df.collect() returns all rows as Python objects but doesn't format them.",
            },
        ],
    },
    "spark_ops": {
        "id": "spark_ops",
        "title": "Spark Operations",
        "description": "Master transformations and actions",
        "xp_reward": 100,
        "topic_id": "spark",
        "exercises": [
            {
                "id": "spark_ops_1",
                "type": "multiple_choice",
                "question": "Which is a transformation in Spark?",
                "options": [
                    "collect()",
                    "map()",
                    "count()",
                    "show()",
                ],
                "correct_answer": 1,
                "explanation_correct": "map() is a transformation — it returns a new RDD/DataFrame without triggering execution. Transformations are lazy and only run when an action is called.",
                "explanation_wrong": "collect(), count(), and show() are all actions — they trigger actual computation. map() is a lazy transformation that just defines a new computation step.",
            },
        ],
    },
    "delta_intro": {
        "id": "delta_intro",
        "title": "Introduction to Delta Lake",
        "description": "Understand Delta Lake fundamentals",
        "xp_reward": 100,
        "topic_id": "delta",
        "exercises": [
            {
                "id": "delta_intro_1",
                "type": "multiple_choice",
                "question": "What problem does Delta Lake solve?",
                "options": [
                    "Lack of ACID transactions in data lakes",
                    "Slow query performance",
                    "Limited storage capacity",
                    "None of the above",
                ],
                "correct_answer": 0,
                "explanation_correct": "Delta Lake brings ACID transactions to data lakes — preventing partial writes, dirty reads, and data corruption that plague standard Parquet-based lakes.",
                "explanation_wrong": "Delta Lake's primary value is ACID transactions. Standard data lakes (Parquet/CSV on object storage) lack transactional guarantees, which leads to data consistency issues.",
            },
        ],
    },
    "delta_acid": {
        "id": "delta_acid",
        "title": "Delta Lake ACID",
        "description": "Learn about ACID transactions",
        "xp_reward": 100,
        "topic_id": "delta",
        "exercises": [
            {
                "id": "delta_acid_1",
                "type": "fill_blank",
                "question": "Delta Lake provides _______ transactions, ensuring data consistency.",
                "correct_answer": "ACID",
                "explanation_correct": "ACID stands for Atomicity, Consistency, Isolation, Durability — the four properties that guarantee database transactions are processed reliably.",
                "explanation_wrong": "The answer is 'ACID'. Delta Lake uses a transaction log (_delta_log) to provide Atomicity, Consistency, Isolation, and Durability on top of object storage.",
            },
        ],
    },
    "delta_timetravel": {
        "id": "delta_timetravel",
        "title": "Delta Lake Time Travel",
        "description": "Query historical data versions",
        "xp_reward": 100,
        "topic_id": "delta",
        "exercises": [
            {
                "id": "delta_tt_1",
                "type": "multiple_choice",
                "question": "What does Delta Lake Time Travel allow you to do?",
                "options": [
                    "Query previous versions of a table",
                    "Travel back in time",
                    "Predict future data",
                    "None of the above",
                ],
                "correct_answer": 0,
                "explanation_correct": "Time Travel lets you query any previous snapshot of a Delta table using VERSION AS OF or TIMESTAMP AS OF — great for auditing and rollbacks.",
                "explanation_wrong": "Time Travel means querying historical table versions. Delta's transaction log records every change, so you can read any past state with VERSION AS OF <n>.",
            },
        ],
    },
    "mlflow_tracking": {
        "id": "mlflow_tracking",
        "title": "MLflow Tracking",
        "description": "Track experiments and metrics",
        "xp_reward": 100,
        "topic_id": "mlflow",
        "exercises": [
            {
                "id": "mlflow_track_1",
                "type": "multiple_choice",
                "question": "What does MLflow Tracking help you do?",
                "options": [
                    "Log and compare ML experiments",
                    "Deploy models only",
                    "Create datasets",
                    "Monitor production systems",
                ],
                "correct_answer": 0,
                "explanation_correct": "MLflow Tracking records parameters, metrics, and artifacts for each experiment run — making it easy to compare dozens of model training runs side by side.",
                "explanation_wrong": "MLflow Tracking is about logging experiments, not deployment or monitoring. It stores runs so you can compare hyperparameters and metrics across trials.",
            },
        ],
    },
    "mlflow_registry": {
        "id": "mlflow_registry",
        "title": "MLflow Model Registry",
        "description": "Manage model versions and stages",
        "xp_reward": 100,
        "topic_id": "mlflow",
        "exercises": [
            {
                "id": "mlflow_reg_1",
                "type": "fill_blank",
                "question": "The MLflow _______ Registry manages model versions and deployment stages.",
                "correct_answer": "Model",
                "explanation_correct": "The MLflow Model Registry is a centralized store for managing model versions through lifecycle stages: Staging, Production, and Archived.",
                "explanation_wrong": "The answer is 'Model'. The MLflow Model Registry tracks versions and lets you transition models through stages (Staging → Production) with governance controls.",
            },
        ],
    },
    "unity_intro": {
        "id": "unity_intro",
        "title": "Unity Catalog Basics",
        "description": "Understand catalog, schema, and tables",
        "xp_reward": 100,
        "topic_id": "unity",
        "exercises": [
            {
                "id": "unity_intro_1",
                "type": "multiple_choice",
                "question": "What is Unity Catalog?",
                "options": [
                    "A metadata layer for data governance",
                    "A SQL database",
                    "A data visualization tool",
                    "A machine learning library",
                ],
                "correct_answer": 0,
                "explanation_correct": "Unity Catalog is Databricks' unified governance layer — it manages access control, auditing, and lineage for data and AI assets across all workspaces.",
                "explanation_wrong": "Unity Catalog is not a database or visualization tool. It's a governance layer that sits above your data, controlling who can access what and tracking data lineage.",
            },
        ],
    },
    "unity_namespace": {
        "id": "unity_namespace",
        "title": "Unity Catalog Namespaces",
        "description": "Organize with catalogs and schemas",
        "xp_reward": 100,
        "topic_id": "unity",
        "exercises": [
            {
                "id": "unity_ns_1",
                "type": "fill_blank",
                "question": "In Unity Catalog, the hierarchy is: catalog > _______ > table.",
                "correct_answer": "schema",
                "explanation_correct": "Unity Catalog uses a three-level namespace: catalog > schema > table. A schema (also called a database) groups related tables within a catalog.",
                "explanation_wrong": "The answer is 'schema'. The full path to a table in Unity Catalog is catalog.schema.table — for example, main.sales.orders.",
            },
        ],
    },
}
